name: CI

on:
  push:
  pull_request:

env:
  MIX_ENV: test

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir_version: ['1.14', '1.15', '1.16', '1.17', '1.18']
        otp_version: ['24', '25', '26', '27']
        exclude:
          - elixir_version: '1.14'
            otp_version: '27'
          - elixir_version: '1.15'
            otp_version: '27'
          - elixir_version: '1.16'
            otp_version: '27'
          - elixir_version: '1.17'
            otp_version: '24'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir_version }}
        otp-version: ${{ matrix.otp_version }}

    - name: Restore dependencies and _build cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Build project
      run: mix compile

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run tests
      run: mix test

    - name: Run credo
      run: mix credo --strict
